# Generated by Django 3.0.6 on 2020-07-02 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0004_applicationentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationentry',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
