# Generated by Django 3.0.6 on 2020-07-03 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0007_auto_20200703_0523'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='comment',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
